language: python
dist: xenial
python:
  - "2.7"
  - "3.7"
cache: pip
services:
  - docker

matrix:
  env:
    - TEST=fedora
    - TEST=centos7
    - TEST=centos8

install:
  - pip install -U pip
  - pip --version
  - pip install ansible ansible-lint yamllint flake8 molecule docker
  - ansible --version
  - ansible-lint --version
  - yamllint --version
  - flake8 --version
  - molecule --version

script:
  # flake8 is not guaranteed to run on lint, do that before testing
  - flake8 $(find . -name '*.py')
  - molecule test -s "${TEST}"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
