galaxy_info:
  author: David Roble
  description: Install certificates using the update-ca-trust command
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
