# TODO These tasks should be considered for addition to the ansible
#      rhsm_repositories module, which would remove the need to set facts to
#      ensure idempotence when using the command module.
- name: Unset subscription-manager release
  action: "{{ _rhsm_release_task }}"
  args:
    release: null
  when: rhsm_release_unset

- name: Set subscription-manager release
  action: "{{ _rhsm_release_task }}"
  args:
    release: "{{ rhsm_release }}"
  when: rhsm_release
