galaxy_info:
  author: Sean Myers
  destiption: Manage the creation and destruction of openstack resources
              for running molecule in a shared CI environment.
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4  # noqa 701 - ignore missing "platforms" def

  galaxy_tags:
    - oasis
    - molecule

dependencies: []
