dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: molecule_docker_ci_fedora
    image: fedora:latest
    ## Remove 'image' above and uncomment the following to run systemd in Docker
    # image: centos/systemd
    # privileged: true
    # command: /usr/lib/systemd/systemd --system
    # volumes:
    #   - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    converge: ../shared/playbook.yml
    create: ../shared/create.yml
    destroy: ../shared/destroy.yml
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: testinfra
  options:
    # Add a -v so you see the individual test names,
    # particularly useful with parameterized tests
    v: true
  lint:
    name: flake8
  # Using the shared directory is useful for sharing tests across scenarios,
  # but is not a requirement. For scenario specific tests, add the appropriate
  # file path to the test or test directory below
  additional_files_or_dirs:
    - ../../shared/tests
