galaxy_info:
  author: Greg Hellings
  description: |-
    Installs, and optionally removes old, network configuration scripts
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis

dependencies: []
