dependency:
  name: galaxy
driver:
  name: openstack
lint:
  name: yamllint
  options:
    config-file: tests/yamllint.yml
platforms:
  - name: test-firewalld
    image: rhel-7.4-server-x86_64-updated
    flavor: m1.medium
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  playbooks:
    prepare: ../shared/prepare.yml
    converge: ../shared/playbook.yml
scenario:
  name: openstack
verifier:
  name: testinfra
  lint:
    name: flake8
  directory: ../shared/
