galaxy_info:
  role_name: openstack_provision
  author: Greg Hellings
  description: Provisions OpenStack hosts and adds them to inventory groups
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7

  galaxy_tags:
    - oasis
    - openstack
    - provisioning

dependencies: []
